# PIM ISO Catalog
# Managed ISOs for automated installations
#
# Each file in isos.d/*.yml defines ISO entries directly.
# Use 'pim iso add' to interactively add new ISOs.
#
# Example entry (uncomment and update checksum):
# debian-12-netinst:
#   name: Debian 12 Bookworm Netinst
#   url: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.8.0-amd64-netinst.iso
#   checksum: sha256:04396d12b0f377958a070c38a923c227832fa3b3e18ddc013936ecf492e9fbb3
#   filename: debian-12.8.0-amd64-netinst.iso
#   architecture: amd64
